Adjust error handling in MediaWiki update script
This removes the set

diff --git a/k8s/jobs/mediawikiUpdate.yaml b/k8s/jobs/mediawikiUpdate.yaml
--- a/k8s/jobs/mediawikiUpdate.yaml
+++ b/k8s/jobs/mediawikiUpdate.yaml
@@ -33,8 +33,12 @@ spec:
                 export MW_INSTALL_PATH=/var/www/html/w/
 
                 log_info "Running MediaWiki update.php for ${WBS_DOMAIN}"
+                
+                # temporarily don't exit on error so we can act on the status
+                set +e
                 php /var/www/html/w/maintenance/run.php update --quick
                 status=$?
+                set -e
                 if [ "$status" -eq 0 ]; then
                   log_info "update.php completed successfully for ${WBS_DOMAIN}"
                   log_info "'run.php update --quick' exited with code 0"
